---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: default
  name: prow-pipeline
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: prow-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prow-pipeline
subjects:
- kind: ServiceAccount
  name: prow-pipeline
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prow-pipeline
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - pipelineresources
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - prow.k8s.io
  resources:
  - prowjobs
  - prowjobs/status
  verbs:
  - get
  - list
  - watch
  - update
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: prow-pipeline
  labels:
    app: prow-pipeline
spec:
  replicas: 1 # Do not scale up.
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prow-pipeline
  template:
    metadata:
      labels:
        app: prow-pipeline
    spec:
      serviceAccountName: prow-pipeline
      containers:
      - name: pipeline
        image: gcr.io/k8s-prow/pipeline:v20190814-9981dc3c5
        args:
        - --config=/etc/config/config.yaml
        volumeMounts:
        - mountPath: /etc/config
          name: config
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: config
