apiVersion: v1
kind: ServiceAccount
metadata:
  name: robot
  #  namespace: catspace
secrets:
- name: robot-secret
---
#apiVersion: v1
#kind: Secret
#metadata:
#  name: robot-secret
#  annotations:
#    kubernetes.io/service-account.name: robot
#type: kubernetes.io/service-account-token
#---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: robot-cluster
subjects:
  - kind: ServiceAccount
    name: robot
    namespace: default
roleRef:
  kind: ClusterRole
  #name: cluster-admin
  name: robot-cluster
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: robot-cluster
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs: ["*"]
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs: ["*"]
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs: ["*"]
  - apiGroups:
      - networking.istio.io
    resources:
      - virtualservices
      - virtualservices/status
      - destinationrules
      - destinationrules/status
    verbs: ["*"]
